RAW_DATA = [
    {"email": "ivan.petrov@abv.bg", "source": "LinkedIn Leak 2021", "date": "2021-05-14"},
    {"email": "m_georgieva@gmail.com", "source": "Adobe Breach", "date": "2013-10-04"},
    {"email": "stefan88@mail.bg", "source": "Canva Hack", "date": "2019-05-24"},
    {"email": "admin@breacherr.io", "source": "Internal Test Leak", "date": "2024-01-10"},
    {"email": "elena_v@yahoo.com", "source": "Dropbox Security Incident", "date": "2012-08-01"},
    {"email": "k.stoyanov@dir.bg", "source": "Fitness App DB", "date": "2020-02-18"},
    {"email": "dimitar.berbatov@gmail.com", "source": "MyFitnessPal Leak", "date": "2018-02-28"},
    {"email": "v.kolev@outlook.bg", "source": "Forum Security Breach", "date": "2016-07-15"},
    {"email": "desi_slava92@gmail.com", "source": "Zomato Data Leak", "date": "2017-05-17"},
    {"email": "hr_manager@jobs.bg", "source": "Recruitment Portal Hack", "date": "2022-09-30"},
    {"email": "support@bank.bg", "source": "Fintech Platform Leak", "date": "2023-03-12"},
    {"email": "alex_p@icloud.com", "source": "Wattpad Data Breach", "date": "2020-06-20"},
    {"email": "petya_ivanova@abv.bg", "source": "E-commerce Shop Leak", "date": "2021-11-02"},
    {"email": "boris.t@mail.bg", "source": "Gaming Forum Hack", "date": "2015-04-19"},
    {"email": "maria.k@protonmail.com", "source": "Crypto Wallet Phishing DB", "date": "2022-12-05"},
    {"email": "office@startup.bg", "source": "HubSpot Contact Leak", "date": "2022-03-01"},
    {"email": "vladislav_87@yahoo.com", "source": "Tumblr Breach", "date": "2013-05-10"},
    {"email": "gergana.n@abv.bg", "source": "Local Courier DB Hack", "date": "2024-02-14"},
    {"email": "nick_dev@gmail.com", "source": "Github Credential Leak", "date": "2021-08-22"},
    {"email": "test_user@example.com", "source": "Verification System Breach", "date": "2023-07-07"}
]